application: devfest-2015
version: 1
runtime: php55
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: app\favicon.ico
  upload: favicon\.ico
  
- url: /apple-touch-icon\.png
  static_files: app\apple-touch-icon.png
  upload: apple-touch-icon\.png

- url: /robots\.txt
  static_files: app\robots.txt
  upload: robots\.txt

- url: (.*)/
  static_files: app\1/index.html
  upload: app

- url: (.*)
  static_files: app\1
  upload: app